name: Pytest and Black
    
on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: 
        pip install setuptools
        pip install wheel
        pip install git+https://github.com/ocjr/timeular-api-final.git
    - name: Run pytest
      env:
        MY_APIKEY: ${{ secrets.MY_APIKEY }}
        MY_APISECRET: ${{ secrets.MY_APISECRET }}
      run: pytest
    - name: Run black
      run: black .
    - name: Run mypy
      run: mypy --ignore-missing-imports src/
